### ISSUE TITLE
Use action after semantic release

### ISSUE THREAD

**Issue by scastria** [StevenJDH/action-tagger#1]
I was trying to find an action in the marketplace that did both:
1. Generate release and version number based on commit messages following semantic versioning commit message format standards
2. Create/Move tags

The official semantic release action ONLY decides on the next version number, like v1.2.3, and creates the release and tags with v1.2.3.  However, it does NOT move the convenience tags, like v1 and v1.2, to the same commit hash has v1.2.3.  These convenience tags allow a consumer to specify only v1 or v1.2 and automatically get upgrades to that same major and minor release train.

Therefore, I found your action which handles the second part.  However, your action ONLY works inside a push tag or release event.  I tried invoking your action at the end of the semantic release workflow, but GitHub prevents workflows triggering other workflows by design.

If you were to enhance your action to add a new input, like `release_version`, so that if specified, your code would ignore the GITHUB_REF and use the release version passed in as input.

**Comment by StevenJDH** [comment]
Hey @scastria, thanks for providing this suggestion. I will add it to my list for future considerations. In the meantime, it may be possible to pass a release version using the existing action-tagger in its current state by overriding `GITHUB_REF` just for that step. I haven't tested it, but it sounds like it would work. Here is an example:

```yaml
- name: Foobar Release
  id: foobar
  uses: example/foobar-release@v1

- name: Tag Release
  id: action-tagger
  uses: stevenjdh/action-tagger@v1
  with:
    set-latest-tag: true
  env:
    GITHUB_REF: refs/tags/${{ steps.foobar.outputs.version }}
```

Let me know if this works. By the way, I think GitHub does allow workflows triggering other workflows as discussed [here](https://stackoverflow.com/questions/71952762/how-to-trigger-a-workflow-from-another-workflow-using-github-actions) with relevant documentation links, which I found interesting for another project I was working on as I skimmed through it, but in the end, I opted to go in a different direction that was less complex for my needs.

**Comment by scastria** [comment]
I did try to override the GITHUB_REF, but it didn’t work. I even copied your entrypoint.sh script into my repo for testing and echoed the GITHUB_REF value. Even though I overrode it, it still echoed as the value GitHub passes in. 

I’m still a beginner at GitHub so there might be multiple ways to trigger a workflow from another workflow. My method was to create 2 workflows. One that triggers on push to main branch which runs the semantic versioning stuff which decides on the new version tag and creates a release and the tag. The second workflow is triggered on release event like your sample showed. I was hoping that the first workflow creating a release would then cause the second workflow due to the release event. It didn’t. I read that it was intentional to not trigger to prevent an infinite recursion of workflows triggering other workflows.

**Comment by StevenJDH** [comment]
No worries. I also ran a few tests, and I can appreciate more the challenge you are facing. Tomorrow I will publish a branch with your feature request implemented since the change was small, and maybe by this weekend I'll publish an official release. Thanks again for your suggestion.

**Comment by StevenJDH** [comment]
I've committed the changes for the feature to a branch. You can use the following now if you want to test before I release officially this weekend.

```yaml
- name: Foobar Release
  id: foobar
  uses: example/foobar-release@v1

- name: Tag Release
  id: action-tagger
  uses: stevenjdh/action-tagger@feature/add_tag_override
  with:
    set-latest-tag: true
    release-version: ${{ steps.foobar.outputs.version }}
```

And just to share, I did some more reading, and it seems the issue for why your approach in your last comment didn't work despite being a good one was because the default GitHub token specifically has safeties that prevent recursion. This is the same token used by action-tagger by default. PATs on the other hand do not have this restriction, and the action already supports overriding this if you want to keep your workflows as is, but then you'll have to remember to update the PAT when it expires. So the most straight forward approach might be to use this new feature and refactor things so that this action runs in the same workflow as your semantic release action.

If there is nothing else related to this, I will close this issue when I merge the PR. Happy new year!
